import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Pixelify_Sans, Poppins, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/_components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const pixelifySans = Pixelify_Sans({
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
                    ${montserrat.variable} ${pixelifySans.variable} 
                    ${poppins.variable} ${sourceCodePro.variable} 
                    antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
